# kitty.toml main purpose: extending/organize wally.toml & adding production

[roblox_production]
id = 123124
version = "0.1.0"
owner = { group = "123456" }

[packages]
runtime = "roblox" # "luau" | "roblox"
registry = { wally = "https://github.com/UpliftGames/wally-index" }

# [packages.core]

[packages.shared]
# if needed default to Packages: "$path" = "Packages" # ex. "Packages/Shared"
# if needed default to none, required when other realm depends on 'shared': "$place" = "game.ReplicatedService.Packages"
limesignal = "caveful-games/limesignal@0.1.5"
react = "jsdotlua/react@17.1.0"
from_url = { url = "https://file.com/file.luau" }
from_path = { path = "ez" }
from_git = { git = "ez.git" }
from_registry = { wally = "https://github.com/jiwonz/wally-index", package = "jiwonz/sans@0.1.0" }

# [packages.server]

# [packages.dev]
