[package]
name = "do-not-publish/not-for-publish"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
private = true

[dependencies]
msgpack-luau = "cipharius/msgpack-luau@0.3.0"
crc16 = "caveful-games/crc16@^0.1.0"
result = "lukadev-0/result@1.0.0"
option = "lukadev-0/option@1.1.0"
threadpool = "caveful-games/threadpool@0.1.3"
limesignal = "caveful-games/limesignal@0.1.5"
datastore-light = "kimpure/datastore-light@0.3.1"
