[package]
name = "jiwonz/kitty"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
warp = "imezx/warp@1.0.5"
koact = "jiwonz/koact@0.2.1"
promise = "lukadev-0/typed-promise@4.0.2"
signal = "sleitnick/signal@2.0.1"
taskqueue = "sleitnick/task-queue@1.0.0"
