[package]
name = "caveful-games/net"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
msgpack-luau = "cipharius/msgpack-luau@0.3.0"
crc16 = "jiwonz/crc16@0.1.0"
option = "lukadev-0/option@1.0.0"
# kit
hook = "caveful-games/hook@^0.1.0"
debugger = "caveful-games/debugger@^0.1.0"
strict = "caveful-games/strict@^0.1.0"
