name = "kitty/flow"
version = "0.1.0"
description = "A collection of utilities related to script timing, flow, control, and coroutines."
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/kitty"
license = "MIT"
includes = ["lib", "README.md"]

[target]
environment = "roblox"
lib = "lib/init.luau"
build_files = ["lib"]

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
signal = { name = "jiwonz/signal", version = "^0.1.0" }
go = { name = "jiwonz/go", version = "^0.2.0" }

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
