name = "kitty/table_helper"
version = "0.1.0"
description = "A helpful table utility that extends RbxUtil's TableUtil"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/kitty"
license = "MIT"
includes = ["pesde.toml", "lib"]

[target]
environment = "roblox"
lib = "lib/init.luau"
build_files = ["lib"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
table-util = { wally = "wally#sleitnick/table-util", version = "^1.2.1" }
greentea = { name = "corecii/greentea", version = "^0.4.11" }
