name = "kitty/root"
version = "0.0.0"
private = true
workspace_members = ["src/*"]

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[engines]
pesde = "^0.6.0"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
